name: Deploy demo to GitHub Pages

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "!v*-*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - name: Build demo
        run: nix build .#nix-eval-demo

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

      - name: Deploy Pages artifact
        id: deployment
        uses: actions/deploy-pages@v4
